- name: provision security group
  ec2_group:
    name: "{{ ec2_sg.name }}"
    description: "{{ ec2_sg.desc }}"
    region: "{{ ec2_region }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: "{{ webdav_port }}"
        to_port: "{{ webdav_port }}"
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        from_port: -1
        to_port: -1
        cidr_ip: 0.0.0.0/0
  register: ec2_group

- name: provision instance
  ec2:
    instance_type: "{{ ec2_type }}"
    image: "{{ ec2_ami }}"
    wait: true
    region: "{{ ec2_region }}"
    key_name: "{{ ec2_key_name }}"
    group_id: "{{ ec2_group.group_id }}"
    exact_count: 1
    count_tag:
      name: webdav
    instance_tags:
      name: webdav
  register: ec2

- name: add dns record
  route53:
    command: create
    zone: "{{ domain }}"
    record: "{{ hostname}}.{{ domain }}"
    type: A
    value: "{{ item.public_ip }}"
  with_items: "{{ ec2.tagged_instances }}"

- name: add to inventory
  add_host:
    hostname: "{{ item.public_ip }}"
    groups: "ec2hosts"
    ansible_ssh_user: ec2-user
    dns_name: "{{ hostname}}.{{ domain }}"
    webdav_port: "{{ webdav_port }}"
  changed_when: False
  with_items: "{{ ec2.tagged_instances }}"

- name: wait for instance is online
  wait_for: port=22 host={{ item.public_ip }}
  with_items: "{{ ec2.tagged_instances }}"
